### ISSUE TITLE
Migrate documentation to a better platform 

### ISSUE THREAD

**Issue by nsnave** [seunomonije/mclang#17]
With the growing amount of documentation, a markdown Readme is no longer sufficient to handle our documentation so we need to migrate it to another platform -- maybe Read the Docs or GitHub Wiki.

**Comment by robertsoule** [comment]
GitHub wiki seems like a good plan.

**Comment by nsnave** [comment]
I migrated the docs to Github Wiki but a couple sections need to be updated. Will create a new issue for updates...
